### ISSUE TITLE
Please include working demo of OpenTor-X and info about how we can test run it on a local machine before uploading! Thanks!

### ISSUE THREAD

**Issue by roboirc** [ajm113/OpenTor-X#5]

**Comment by ajm113** [comment]
I apologize... I don't really plan on doing anything more to at this time since this project is really old and the documentation assumes you know some simple server stack knowledge. I was planning on re-writing this project into GoLang and React if people really want to see this happen to remove the middleman of Apache/Nginx. That way I can fire up a Heroku instance that can spin up and down cheaply for anyone wanting to test the waters and have some practical documentation on knowing how to quickly spin this up or package it all in a simple Docker container you can fire up in just a few commands.

I have a two major projects right now in the works. If things start to slow down and I can find some people behind this I'll continue on OpenTor-X 2.0 version.

Edit: Of course, I'll review and manager pull requests that come in for this project if you wish to make a change.

**Comment by roboirc** [comment]
Thanks for your reply!
